//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForms_Julio_F_Higuera
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int EmpresaId { get; set; }
        public string Nombre { get; set; }
        public string NIF { get; set; }
        public string Telefono { get; set; }
        public string PersonaContacto { get; set; }
        public string Direccion { get; set; }
        public System.DateTime Convenio { get; set; }
    }
}
