//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCine_JulioF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        public int SesionId { get; set; }
        public string Sala { get; set; }
        public string DiaSemana { get; set; }
        public System.DateTime Comienzo { get; set; }
        public System.DateTime FinMax { get; set; }
        public float Precio { get; set; }
        public int Aforo { get; set; }
    }
}
